djangpro/accounts/urls.py
from django.conf.urls import url
from . import views

app_name='accounts'

urlpatterns=[url(r'^signup/$',views.signup_view, name="signup"),
			 url(r'^login/$',views.login_view, name="login"),
			 url(r'^logout/$',views.logout_view,name="logout"),
]

djangpro/articles/urls.py
from . import views
from django.conf.urls import url
from django.contrib import admin

app_name="articles"
urlpatterns= [
      url(r'^$',views.article_list, name="list"),
      url(r'^create/$',views.article_create,name="create"),
      url(r'^(?P<slug>[\w-]+)/$',views.article_detail, name="detail"),
]

djangpro/djangpro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from . import views
from articles import views as article_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/',include('articles.urls')),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^about/$',views.about),
    url(r'^$',article_views.article_list, name="home"),
]
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangpro/accounts/models.py
from django.db import models

# Create your models here.

djangpro/articles/models.py
from django.db import models
from PIL import Image
from django.contrib.auth.models import User
from io import StringIO,BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys


# Create your models here.
class Article(models.Model):
	title=models.CharField(max_length=100)
	slug=models.SlugField()
	body=models.TextField()
	date=models.DateTimeField(auto_now_add=True)
	author=models.ForeignKey(User,default=None, on_delete=models.PROTECT)
	thumb=models.ImageField(default="default.png", blank="True")
	def __str__(self):
		return self.title

	def snippet(self):
		return self.body[:50]+'...'

	

djangpro/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
	class Meta:
		model=models.Article
		fields=['title','body','slug','thumb']

djangpro/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
	if request.method =='POST':
		form=UserCreationForm(request.POST)
		if form.is_valid():
			user=form.save()
			login(request,user)
			return redirect("articles:list")
	else: 
		form=UserCreationForm()
	return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
	if request.method=="POST":
		form=AuthenticationForm(data=request.POST)
		if form.is_valid():
			user=form.get_user()
			login(request,user)
			if 'next' in request.POST:
				return redirect(request.POST.get('next'))
			else:
				return redirect("articles:list")
	else:
		form=AuthenticationForm()
	return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
	if request.method=="POST":
		logout(request)
		return redirect('articles:list')



djangpro/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from . import forms
from django.contrib.auth.decorators import login_required
# Create your views here.
def article_list(request):
	articles=Article.objects.all().order_by('date')
	return render(request,"articles/article_list.html",{'articles':articles})

def article_detail(request,slug):
	article=Article.objects.get(slug=slug)
	return render(request,"articles/article_detail.html",{'article':article})

@login_required(login_url="/accounts/login/")
def article_create(request):
	if request.method=="POST":
		form=forms.CreateArticle(request.POST,request.FILES)
		if form.is_valid():
			instance=form.save(commit=False)
			instance.author=request.user
			instance.save()
			return redirect('articles:list')
	else:
		form=forms.CreateArticle()
	return render(request,'articles/article_create.html',{'form':form})

djangpro/djangpro/views.py
from django.http import HttpResponse
from django.shortcuts import render
def about(request):
	return render(request,"about.html")
def homepage(request):
	return render(request,"home.html")

djangpro/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<h1>LOGIN</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="POST">
{% csrf_token %}
{{ form }}
{% if request.GET.next %}
	<input type="hidden" name="next" value="{{ request.GET.next }}">
{% endif %}
<input type="submit" value="Login">
</form>
{% endblock %}

djangpro/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<h1>SIGNUP</h1>
<form class="site-form" action="/accounts/signup/" method="POST">
{% csrf_token %}
{{ form }}
<input type= "submit" value="SIGNUP">
</form>
{% endblock %}

djangpro/articles/templates/articles/article_create.html
{% extends 'base.html' %}
{% block content %}
<div class="create-article">
<h2>Create Article</h2>
<form class="site-form" action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{ form }}
<input type="submit" value="Create">
</form>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

djangpro/articles/templates/articles/article_detail.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>
		article
	</title>
	<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
<header class="wrapper">
<form class="back" action="{% url 'home' %}" method="POST">
			{% csrf_token %}
			<button type="Submit">back</button>
			</form>
<nav>
	<ul>
	{% if user.is_authenticated %}
		<li>
			<form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
			{% csrf_token %}
			<button type="Submit">LOGOUT</button>
			</form>
		</li>
		<li><form class="logout-link" action="{% url 'articles:create' %}" method="POST">
			{% csrf_token %}
			<button type="Submit">NEW ARTICLE</button>
			</form>
		</li>
	{% else %}
	<li><form class="logout-link" action="{% url 'accounts:login' %}" method="POST">
			{% csrf_token %}
			<button type="Submit">LOGIN</button>
			</form></li>
	<li><form class="logout-link" action="{% url 'accounts:signup' %}" method="POST">
			{% csrf_token %}
			<button type="Submit">SIGNUP</button>
			</form></li>
	{% endif %}
	</ul>
</nav>
</header>
<div class="article_detail">
	<div class= "article">
		<div class="image">
		<img src="{{ article.thumb.url }}"/></div>
		<h2>{{ article.title }}</h2>
		<p>{{ article.body }}</p>
		<p>{{ article.date }}</p>
	</div>
</div>
</body>
</html>

djangpro/articles/templates/articles/article_list.html
{% extends 'base.html' %}
{% block content %}
<p class="art">Current Mood</p>
<div class="articles">
{% for article in articles %}
<div class="article">
<h1><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h1>
<p>{{ article.snippet }}</p>
<p>{{article.date}}</p>
<p class="author">added by {{ article.author.username }}</p>
</div>
{% endfor %}
</div>
{% endblock %}

djangpro/templates/about.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>hi</h1>
</body>
</html>

djangpro/templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>
		article
	</title>
	<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
<header class="wrapper">
<h1 class="nebula"><a href="{% url 'home' %}"><b>NEBULOUS</b></a></h1>
<nav>
	<ul>
	{% if user.is_authenticated %}
		<li>
			<form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
			{% csrf_token %}
			<button type="Submit">LOGOUT</button>
			</form>
		</li>
		<li><form class="logout-link" action="{% url 'articles:create' %}" method="POST">
			{% csrf_token %}
			<button type="Submit">NEW ARTICLE</button>
			</form>
		</li>
	{% else %}
	<li><form class="logout-link" action="{% url 'accounts:login' %}" method="POST">
			{% csrf_token %}
			<button type="Submit">LOGIN</button>
			</form></li>
	<li><form class="logout-link" action="{% url 'accounts:signup' %}" method="POST">
			{% csrf_token %}
			<button type="Submit">SIGNUP</button>
			</form></li>
	{% endif %}
	</ul>
</nav>
</header>
<div class="wrapper">
	{% block content %}
	{% endblock %}
</div>
</body>
</html>